<a href="https://colab.research.google.com/github/VishalSingh1703/ML-Practice/blob/main/Min_Max.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [4]:
v = np.array([1, 40, 2, -3])

# find the max and min values:
minval = np.min(v)
maxval = np.max(v)


minidx = np.argmin(v)
maxidx = np.argmax(v)

print(v)
print('The min value is: ' + str(minval))
print('And its index is: ' + str(minidx))
print('The max value is: ' + str(maxval))
print('And its index is: ' + str(maxidx))

[ 1 40  2 -3]
The min value is: -3
And its index is: 3
The max value is: 40
And its index is: 1


In [9]:
M = np.array([
    [0, 1, 10],
    [20, 8, 5]
])

print(M), print(' ')

m1 = np.min(M) # Return the minimum of the entire matrix
m1idx = np.argmin(M)
m2 = np.min(M, axis = 0) # Returns the min of each col
m2idx = np.argmin(M, axis = 0) # Returns the min of each col
m3 = np.min(M, axis = 1) # Returns the min of each row
m3idx = np.argmin(M, axis = 1) # Returns the min of each row

print('The min values are:             ' + str(m1))
print('And its index are:              ' + str(m1idx))
print('The min of each col values are: ' + str(m2))
print('And their indexes are:          ' + str(m2idx))
print('The min values of each row are: ' + str(m3))
print('And their indexes are:          ' + str(m3idx))

[[ 0  1 10]
 [20  8  5]]
 
The min values are:             0
And its index are:              0
The min of each col values are: [0 1 5]
And their indexes are:          [0 0 1]
The min values of each row are: [0 5]
And their indexes are:          [0 2]


In [10]:
v = torch.tensor([ 1, 40, 2, -3 ])

minval = torch.min(v)
maxval = torch.max(v)

minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print(v)
print('The min value is: ' + str(minval))
print('And its index is: ' + str(minidx))
print('The max value is: ' + str(maxval))
print('And its index is: ' + str(maxidx))

tensor([ 1, 40,  2, -3])
The min value is: tensor(-3)
And its index is: tensor(3)
The max value is: tensor(40)
And its index is: tensor(1)


In [15]:
M = torch.tensor([
    [0, 1, 10],
    [20, 8, 5]
])

m1 = torch.min(M) # Return the minimum of the entire matrix
m1idx = torch.argmin(M)
m2 = torch.min(M, axis = 0) # Returns the min of each col
m2idx = torch.argmin(M, axis = 0) # Returns the min of each col
m3 = torch.min(M, axis = 1) # Returns the min of each row
m3idx = torch.argmin(M, axis = 1) # Returns the min of each row

print('The min values are:             ' + str(m1))
print('And its index are:              ' + str(m1idx))
print('The min of each col values are: ' + str(m2.values))
print('And their indexes are:          ' + str(m2idx))
print('The min values of each row are: ' + str(m3.values))
print('And their indexes are:          ' + str(m3idx))

The min values are:             tensor(0)
And its index are:              tensor(0)
The min of each col values are: tensor([0, 1, 5])
And their indexes are:          tensor([0, 0, 1])
The min values of each row are: tensor([0, 5])
And their indexes are:          tensor([0, 2])
3
