<a href="https://colab.research.google.com/github/VishalSingh1703/ML-Practice/blob/main/PythonML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
fun = lambda x : x**2 - x
fun(5)

20

In [18]:
import random

x = random.randint(1, 10)
print("x is large") if x>5 else print("x is small")

lst = [ i**2 for i in range(10) if i>5]
lst

x is small


[36, 49, 64, 81]

In [22]:
txt = ['hello', 'hi', 'why', 'you', 'guy']
t = [i[0] for i in txt]
t

['h', 'h', 'w', 'y', 'g']

In [26]:
newlist = [' ']*10

for i in range(10):
  if i%2 == 1:
    newlist[i] = 'odd'
  else:
    newlist[i] = 'i'

newlist = [i if i%2 == 0 else 'odd' for i in range(10)]

newlist

[0, 'odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd']

In [45]:
import numpy as np

x = np.array (
    [
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]
    ]
)

z = np.array([10, 20, 30])
x.shape # returns the dimensions of the vector, in this case 4, 3
y = np.zeros(x.shape)
for i in range(x.shape[0]):
  y[i:] = x[i:] + z




In [57]:
v = np.array([-1, 0, 1, 0], ndmin = 2).T

print(x)
print(v)
print(x+v)
print(x*v)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[-1]
 [ 0]
 [ 1]
 [ 0]]
[[0 1 2]
 [2 3 4]
 [4 5 6]
 [4 5 6]]
[[-1 -2 -3]
 [ 0  0  0]
 [ 3  4  5]
 [ 0  0  0]]


In [68]:
M = np.arange(9)
M = np.reshape(M, (3, 3 ))
print(M), print(' ')

c = np.tile(M, (3, 1))
print(c), print(' ')


[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
 


(None, None)

In [76]:
import string
letters = string.ascii_lowercase

for i in range(len(letters)):
  print(f'{letters[i]} is the {i+1}th letter')

a is the 1th letter
b is the 2th letter
c is the 3th letter
d is the 4th letter
e is the 5th letter
f is the 6th letter
g is the 7th letter
h is the 8th letter
i is the 9th letter
j is the 10th letter
k is the 11th letter
l is the 12th letter
m is the 13th letter
n is the 14th letter
o is the 15th letter
p is the 16th letter
q is the 17th letter
r is the 18th letter
s is the 19th letter
t is the 20th letter
u is the 21th letter
v is the 22th letter
w is the 23th letter
x is the 24th letter
y is the 25th letter
z is the 26th letter
